<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DeterminaConfiguracionServicioWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/DeterminaConfiguracionServicioWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/DeterminaConfiguracionServicioWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://st.org/">
    <import location="DeterminaConfiguracionServicio.wsdl" namespace="http://st.org/"/>
    <plnk:partnerLinkType name="DeterminaConfiguracionServicioLinkType">
        <plnk:role name="DeterminaConfiguracionServicioRole" portType="ns:DeterminaConfiguracionServicio"/>
    </plnk:partnerLinkType>
</definitions>
