<?xml version="1.0" encoding="UTF-8"?>
<definitions name="switchTransaccionalSincronico" targetNamespace="http://j2ee.netbeans.org/wsdl/switchTransaccionalSincronico"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://xml.netbeans.org/schema/switchTransaccionalSincrónico" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/switchTransaccionalSincronico">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/switchTransaccionalSincronico">
            <xsd:import namespace="http://xml.netbeans.org/schema/switchTransaccionalSincrónico" schemaLocation="switchTransaccionalSincronico.xsd"/>
        </xsd:schema>
    </types>
    <message name="switchTransaccionalSincronicoOperationRequest">
        <part name="requerimiento" element="ns:requerimiento"/>
    </message>
    <message name="switchTransaccionalSincronicoOperationReply">
        <part name="respuesta" element="ns:respuesta"/>
    </message>
    <portType name="switchTransaccionalSincronicoPortType">
        <operation name="switchTransaccionalSincronicoOperation">
            <input name="input1" message="tns:switchTransaccionalSincronicoOperationRequest"/>
            <output name="output1" message="tns:switchTransaccionalSincronicoOperationReply"/>
        </operation>
    </portType>
    <binding name="switchTransaccionalSincronicoBinding" type="tns:switchTransaccionalSincronicoPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="switchTransaccionalSincronicoOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="switchTransaccionalSincronicoService">
        <port name="switchTransaccionalSincronicoPort" binding="tns:switchTransaccionalSincronicoBinding">
            <soap:address location="http://localhost:18181/switchTransaccionalSincronicoService/switchTransaccionalSincronicoPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="switchTransaccionalSincronico1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="switchTransaccionalSincronicoPortTypeRole" portType="tns:switchTransaccionalSincronicoPortType"/>
    </plnk:partnerLinkType>
</definitions>
