<?xml version="1.0" encoding="UTF-8"?>
<definitions name="libreDeudaAutomotor" targetNamespace="http://j2ee.netbeans.org/wsdl/libreDeudaAutomotor"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://xml.netbeans.org/schema/prestacionMedica" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/libreDeudaAutomotor">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/libreDeudaAutomotor">
            <xsd:import namespace="http://xml.netbeans.org/schema/prestacionMedica" schemaLocation="libreDeudaAutomotor.xsd"/>
        </xsd:schema>
    </types>
    <message name="libreDeudaAutomotorOperationRequest">
        <part name="requerimiento" element="ns:requerimiento"/>
    </message>
    <message name="libreDeudaAutomotorOperationReply">
        <part name="respuesta" element="ns:respuesta"/>
    </message>
    <message name="libreDeudaAutomotorOperationFault">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="libreDeudaAutomotorPortType">
        <operation name="libreDeudaAutomotorOperation">
            <input name="input1" message="tns:libreDeudaAutomotorOperationRequest"/>
            <output name="output1" message="tns:libreDeudaAutomotorOperationReply"/>
            <fault name="fault1" message="tns:libreDeudaAutomotorOperationFault"/>
        </operation>
    </portType>
    <binding name="libreDeudaAutomotorBinding" type="tns:libreDeudaAutomotorPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="libreDeudaAutomotorOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
            <fault name="fault1">
                <soap:fault use="literal" name="fault1"/>
            </fault>
        </operation>
    </binding>
    <service name="libreDeudaAutomotorService">
        <port name="libreDeudaAutomotorPort" binding="tns:libreDeudaAutomotorBinding">
            <soap:address location="http://localhost:18181/libreDeudaAutomotorService/libreDeudaAutomotorPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="libreDeudaAutomotor1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="libreDeudaAutomotorPortTypeRole" portType="tns:libreDeudaAutomotorPortType"/>
    </plnk:partnerLinkType>
</definitions>
